Module2 task1
htmlacademy-javascript/173700-keksobooking-22 pull request #2
Opened 2021-02-04 12:01 UTC by aoihikaru

Выполнено:
1. Добавлена ссылка на скрипт в index.html;
2. Создана функция для выбора случайного целого числа из диапазона (на основе алгоритма из MDN);
3. Создана функция для выбора случайного десятичного числа с указанным числом знаков после запятой;

2021-02-04 13:40 UTC, polina-prokofieva requested changes

2021-02-04 13:40 UTC, polina-prokofieva commented on js/main.js
> +// const getRandomIntegerNumber
У функций должно быть имя, так что лучше его разкомментировать и присвоить ему функцию.

2021-02-04 13:40 UTC, polina-prokofieva commented on js/main.js
> +  }
Эта часть в функциях практически идентична. Чтобы не было дублирования кода (Д14), его нужно вынести в отдельную функцию. Тут по сути можно сделать одну функцию на основании другой. Функция получения целого числа - это, как функция получения числа с плавающей точкой, с третьим параметром, равным 0. Плюс можно ещё добавить проверку, что входные параметры целые (но тогда нужно что-то делать, если это не так - например, писать ошибку в консоль).

2021-02-04 13:40 UTC, polina-prokofieva commented on js/main.js
> +    return Math.round(Math.random() * (firstNumber - lastNumber) + lastNumber);
Эти две строчки очень похожи. Тут можно обойтись одной, если в начале функции создать две переменные, например start и end, записать в start - меньшее значение, а в end - большее.

2021-02-04 15:50 UTC, aoihikaru commented on js/main.js
> +// const getRandomIntegerNumber
Если я задавала имя переменной, линтер ругается и выдает ошибку "Error      12,7: 'getRandomDecimalNumber' is assigned a value but never used. (no-unused-vars)". Поэтому до повторного использования функции было решено закомментировать наименование, чтобы дз было принято.

2021-02-04 17:24 UTC, polina-prokofieva commented on js/main.js
> +// const getRandomIntegerNumber
Тогда лучше вызвать эти функции в конце файла. А результат вывести в консоль.

2021-02-05 08:49 UTC, polina-prokofieva requested changes

2021-02-05 08:49 UTC, polina-prokofieva commented on js/main.js
> +  if (firstNumber >= 0, lastNumber >= 0) {
Если есть проверка на то, что оба числа положительные, должно быть описано какое-то поведение, в случае, если это не так. Иначе будет возникать ошибка в строчке с return (в случае, если хотя бы одно число отрицательное) и эта проверка получается бессмысленной.

2021-02-08 12:08 UTC, polina-prokofieva approved these changes

2021-02-08 12:08 UTC, merged